/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoGraphics;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import javax.swing.ButtonGroup;
import javax.swing.JColorChooser;

/**
 *
 * @author Bao Anh Luu
 */
public class Frame extends javax.swing.JFrame {

    Color color;
    Graphics g;
    Point p1 = null, p2 = null;

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        ButtonGroup butGroup = new ButtonGroup();
        butGroup.add(radDraw);
        butGroup.add(radDrawFill);
        color = Color.RED;
        g = tabLine.getGraphics();
        radDraw.setSelected(true);
        radDrawFill.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butColor = new javax.swing.JButton();
        radDraw = new javax.swing.JRadioButton();
        radDrawFill = new javax.swing.JRadioButton();
        tab = new javax.swing.JTabbedPane();
        tabLine = new javax.swing.JPanel();
        tabRect = new javax.swing.JPanel();
        tabOval = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butColor.setText("Color");
        butColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butColorActionPerformed(evt);
            }
        });

        radDraw.setText("Draw");

        radDrawFill.setText("Draw & Fill");

        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });

        tabLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabLineMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabLineMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout tabLineLayout = new javax.swing.GroupLayout(tabLine);
        tabLine.setLayout(tabLineLayout);
        tabLineLayout.setHorizontalGroup(
            tabLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        tabLineLayout.setVerticalGroup(
            tabLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        tab.addTab("Line", tabLine);

        tabRect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabRectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabRectMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout tabRectLayout = new javax.swing.GroupLayout(tabRect);
        tabRect.setLayout(tabRectLayout);
        tabRectLayout.setHorizontalGroup(
            tabRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        tabRectLayout.setVerticalGroup(
            tabRectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        tab.addTab("Rect", tabRect);

        tabOval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabOvalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabOvalMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout tabOvalLayout = new javax.swing.GroupLayout(tabOval);
        tabOval.setLayout(tabOvalLayout);
        tabOvalLayout.setHorizontalGroup(
            tabOvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        tabOvalLayout.setVerticalGroup(
            tabOvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        tab.addTab("Oval", tabOval);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(butColor)
                .addGap(41, 41, 41)
                .addComponent(radDraw)
                .addGap(58, 58, 58)
                .addComponent(radDrawFill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butColor)
                    .addComponent(radDraw)
                    .addComponent(radDrawFill))
                .addGap(83, 83, 83)
                .addComponent(tab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butColorActionPerformed
        color = JColorChooser.showDialog(this, "Choose Color", Color.GREEN);
    }//GEN-LAST:event_butColorActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        int index = this.tab.getSelectedIndex();
        switch (index) {
            case 0:
                g = tabLine.getGraphics();
                radDrawFill.setEnabled(false);
                break;
            case 1:
                g = tabRect.getGraphics();
                radDrawFill.setEnabled(true);
                break;
            case 2:
                g = tab.getGraphics();
                radDrawFill.setEnabled(true);
                break;
        }

    }//GEN-LAST:event_tabMouseClicked

    private void tabLineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabLineMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_tabLineMousePressed

    private void tabLineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabLineMouseReleased
        p2 = evt.getPoint();
        g.setColor(color);
        g.drawLine(p1.x, p1.y, p2.x, p2.y);
        p1 = p2 = null;
    }//GEN-LAST:event_tabLineMouseReleased

    private void tabRectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabRectMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_tabRectMousePressed

    private void tabRectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabRectMouseReleased
        p2 = evt.getPoint();
        g.setColor(color);
        if (radDraw.isSelected()) {
            g.drawRect(p1.x, p1.y, Math.abs(p2.x - p1.x), Math.abs(p2.y - p1.y));
        }
        if (radDrawFill.isSelected()) {
            g.fillRect(p1.x, p1.y, Math.abs(p2.x - p1.x), Math.abs(p2.y - p1.y));
        }
        p1 = p2 = null;
    }//GEN-LAST:event_tabRectMouseReleased

    private void tabOvalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabOvalMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_tabOvalMousePressed

    private void tabOvalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabOvalMouseReleased
        p2 = evt.getPoint();
        g.setColor(color);
        if (radDraw.isSelected()) {
            g.drawOval(p1.x, p1.y, Math.abs(p2.x - p1.x), Math.abs(p2.y - p1.y));
        }
        if (radDrawFill.isSelected()) {
            g.fillOval(p1.x, p1.y, Math.abs(p2.x - p1.x), Math.abs(p2.y - p1.y));
        }
        p1 = p2 = null;
    }//GEN-LAST:event_tabOvalMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butColor;
    private javax.swing.JRadioButton radDraw;
    private javax.swing.JRadioButton radDrawFill;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JPanel tabLine;
    private javax.swing.JPanel tabOval;
    private javax.swing.JPanel tabRect;
    // End of variables declaration//GEN-END:variables
}
