/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JTableSQL;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Bao Anh Luu
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
    public Frame() {
        initComponents();
    }

    public JCheckBox getChkCountry() {
        return chkCountry;
    }

    public void setChkCountry(JCheckBox chkCountry) {
        this.chkCountry = chkCountry;
    }

    public JButton getButDelete() {
        return butDelete;
    }

    public void setButDelete(JButton butDelete) {
        this.butDelete = butDelete;
    }

    public JButton getButInsert() {
        return butInsert;
    }

    public void setButInsert(JButton butInsert) {
        this.butInsert = butInsert;
    }

    public JButton getButUpdate() {
        return butUpdate;
    }

    public void setButUpdate(JButton butUpdate) {
        this.butUpdate = butUpdate;
    }

    public JTextField getTxtSeleContactName() {
        return txtSeleContactName;
    }

    public void setTxtSeleContactName(JTextField txtSeleContactName) {
        this.txtSeleContactName = txtSeleContactName;
    }

    public JTextField getTxtSeleOrderID() {
        return txtSeleOrderID;
    }

    public void setTxtSeleOrderID(JTextField txtSeleOrderID) {
        this.txtSeleOrderID = txtSeleOrderID;
    }

    public JCheckBox getChkContactName() {
        return chkContactName;
    }

    public void setChkContactName(JCheckBox chkContactName) {
        this.chkContactName = chkContactName;
    }

    public JCheckBox getChkCustomerID() {
        return chkCustomerID;
    }

    public JTextArea getTxtSelectInfo() {
        return txtSelectInfo;
    }

    public void setTxtSelectInfo(JTextArea txtSelectInfo) {
        this.txtSelectInfo = txtSelectInfo;
    }

    public JButton getButSort() {
        return butSort;
    }

    public void setButSort(JButton butSort) {
        this.butSort = butSort;
    }

    public void setChkCustomerID(JCheckBox chkCustomerID) {
        this.chkCustomerID = chkCustomerID;
    }

    public JCheckBox getChkEmployeeID() {
        return chkEmployeeID;
    }

    public void setChkEmployeeID(JCheckBox chkEmployeeID) {
        this.chkEmployeeID = chkEmployeeID;
    }

    public JCheckBox getChkOrderID() {
        return chkOrderID;
    }

    public void setChkOrderID(JCheckBox chkOrderID) {
        this.chkOrderID = chkOrderID;
    }

    public JTable getTblTable() {
        return tblTable;
    }

    public void setTblTable(JTable tblTable) {
        this.tblTable = tblTable;
    }

    public JButton getButLoad() {
        return butLoad;
    }

    public JComboBox<String> getCbxFilterBy() {
        return cbxFilterBy;
    }

    public void setCbxFilterBy(JComboBox<String> cbxFilterBy) {
        this.cbxFilterBy = cbxFilterBy;
    }

    public void setButLoad(JButton butLoad) {
        this.butLoad = butLoad;
    }

    public JTextField getTxtSearch() {
        return txtSearch;
    }

    public void setTxtSearch(JTextField txtSearch) {
        this.txtSearch = txtSearch;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        butLoad = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        cbxFilterBy = new javax.swing.JComboBox<>();
        chkOrderID = new javax.swing.JCheckBox();
        chkCustomerID = new javax.swing.JCheckBox();
        chkCountry = new javax.swing.JCheckBox();
        chkEmployeeID = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSelectInfo = new javax.swing.JTextArea();
        butSort = new javax.swing.JButton();
        chkContactName = new javax.swing.JCheckBox();
        butInsert = new javax.swing.JButton();
        butUpdate = new javax.swing.JButton();
        butDelete = new javax.swing.JButton();
        txtSeleOrderID = new javax.swing.JTextField();
        txtSeleContactName = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        lblContactName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "CustomerID", "ShipCountry"
            }
        ));
        jScrollPane1.setViewportView(tblTable);

        butLoad.setText("Load");

        chkOrderID.setText("OrderID");

        chkCustomerID.setText("CustomerID");

        chkCountry.setText("ShipCountry");

        chkEmployeeID.setText("EmployeeID");

        txtSelectInfo.setColumns(20);
        txtSelectInfo.setRows(5);
        jScrollPane2.setViewportView(txtSelectInfo);

        butSort.setText("Sort");

        chkContactName.setText("ContactName");

        butInsert.setText("Insert");

        butUpdate.setText("Update");

        butDelete.setText("Delete");

        lblSearch.setText("Search:");

        lblOrderID.setText("OrderID:");

        lblContactName.setText("ContactName:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(butLoad)
                        .addGap(18, 18, 18)
                        .addComponent(butSort))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSearch)
                                    .addComponent(lblOrderID)
                                    .addComponent(lblContactName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSeleContactName, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                        .addGap(86, 86, 86)
                                        .addComponent(butUpdate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSeleOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butInsert))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxFilterBy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(butDelete))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkOrderID)
                                    .addComponent(chkCustomerID)
                                    .addComponent(chkCountry)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(chkContactName))
                                    .addComponent(chkEmployeeID))))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxFilterBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSearch))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butInsert)
                            .addComponent(txtSeleOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butUpdate)
                            .addComponent(txtSeleContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContactName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butLoad)
                            .addComponent(butSort))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkOrderID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkCustomerID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkCountry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkEmployeeID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkContactName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDelete;
    private javax.swing.JButton butInsert;
    private javax.swing.JButton butLoad;
    private javax.swing.JButton butSort;
    private javax.swing.JButton butUpdate;
    private javax.swing.JComboBox<String> cbxFilterBy;
    private javax.swing.JCheckBox chkContactName;
    private javax.swing.JCheckBox chkCountry;
    private javax.swing.JCheckBox chkCustomerID;
    private javax.swing.JCheckBox chkEmployeeID;
    private javax.swing.JCheckBox chkOrderID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblContactName;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSeleContactName;
    private javax.swing.JTextField txtSeleOrderID;
    private javax.swing.JTextArea txtSelectInfo;
    // End of variables declaration//GEN-END:variables
}
